### PR TITLE
Initial Implementation

### PR DESCRIPTION
**Pull request by keithamus**
Before I go too much further with docs & tests I thought I'd push this up so people can review it early, and see if there are any drastic changes that need to be made.

[Rendered Readme here](https://github.com/the-economist-editorial/standard-server/pull/1/files?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8)

### CODE REVIEW

**Comment by sebinsua** [comment]
It seems pretty good to me. I have added my thoughts against the code and docs.

I couldn't seem to find the `errorLogger` middleware within the code. Does it not exist yet? I was going to say that we should make sure it logs stacktraces and stuff like that.

Are there any other middlewares that we might include by default?

I normally add [`connect-requestid`](https://www.npmjs.com/package/connect-requestid) and place this id against the response header and within the logs so that requests, successful or otherwise, can be identified both on the server-side and on the client-side. (The biggest benefit however, is when you are creating microservice platforms and need to recreate stacks from messaging flow through a network - you send the id through to the next service in a request header, and it then picks that up.)

Also, perhaps we could add something like [express-healthcheck](https://www.npmjs.com/package/express-healthcheck) which can be pinged for some basic stats?

**Comment by keithamus** [comment]
> I couldn't seem to find the errorLogger middleware within the code. [...]

This is provided by [`bunyan-request-logger`](https://github.com/ericelliott/bunyan-request-logger) and so isn't actually exposed in our code. I've documented it though as it is available and should be used.

> Are there any other middlewares that we might include by default?

Currently this is just pulling out the middleware from WIF. I very specifically have kept it to this - because I want this to grow organically rather than risking [YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it).

> I normally add something-like connect-requestid [...]

The requestLogger middleware does this already. `request.log` will also log its request id - so nothing else needs to happen with this.

> Perhaps we could add something like express-healthcheck that can be pinged for some basic stats about the health of the service?

I don't think we need this as everywhere we deploy to will have health monitoring for this kind of stuff. 

> Perhaps there could be some way for the service to send metrics to something like Graphite or whatever we plan to use? [...]

Bunyan has been added with the idea that we can stream out logs through an [ELK](https://www.elastic.co/webinars/introduction-elk-stack) stack and use Kibana to get interesting metrics. Of course, right now that isn't the case but this is a not-too-distant-future option (it is currently being worked on in revamp).

BTW, if you use this server and use the error logger middleware, we'll get: (1) success vs errored requests for every request (2) pid, (configured) name, hostname and date/time for every log message that is emitted. (although not memory/uptime - but thats trivial to add so I'll do it).

A bunyan log looks like this:
```js
bunyan.log.info('hi');
```
```json
{"name":"myapp","hostname":"banana.local","pid":40161,"level":30,"msg":"hi","time":"2013-01-04T18:46:23.851Z","v":0}
```

> Since this is connect what IP address will be in req.ip? [...]

Once again I'll cite [YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it). If we find we're doing it enough, we'll chuck it in. We have yet to do this so far though.

> What are your thoughts on pm2? [...]

As we're using Docker, and AWS has autoscaling and health checks - I'm not sure pm2, or in fact any load balancing solution is needed for us. If we do need to load balance I'd much rather deal with it upstream via AWS - and we can automate this through AWS templates.

> Finally, as a meta perspective, I think it would be a good idea to define the purpose, concerns and greater goals of the standard-server in an explicit way [...]

I will add this to the readme.

**Comment by keithamus** [comment]
@sebinsua updates have been made. Please re-review.

@Economist-Editorial - someone else please review :smile:

**Comment by sebinsua** [comment]
Looks awesome to me. :full_moon_with_face:

**Pull request merged**
